"""The two MIMIC-IV tables, both from one evaluation.

Table A  EASE by estimand, every method on the identical control panel.
Table B  Risk ratios for the combined population, same methods, same cohort,
         same pre-training arm.

Both read results/full_insample_ease_<ARM>.csv, so the EASE printed in the
funnel figure, the EASE tabulated in Table A and the effects in Table B cannot
drift apart.

    python make_mimic_tables.py

Output: results/tab_mimic_ease.tex, results/tab_mimic_rr.tex
"""
from __future__ import annotations

import os

from rwet import paths

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = str(paths.RESULTS)
ARM = os.environ.get("ARM", "F64").upper()

ROWS = [("Unadjusted", "Unadjusted"),
        ("X", "Baseline (observed covariates)"),
        ("BCAUSS", "BCAUSS"),
        ("CausalEGM", "CausalEGM"),
        ("Z0", r"\methodName\ without debiasing"),
        ("XZ", r"\methodName")]
BASELINES = ("BCAUSS", "CausalEGM")


def base_se():
    """Refit-bootstrap standard errors for the neural comparators.

    These are not estimand-specific and come from the 20-replicate refit
    bootstrap in results/mimic_with_baselines.csv rather than from the
    influence function, because neither comparator exposes one. Read from the
    file rather than transcribed, so the table cannot drift from its source.
    """
    p = os.path.join(OUT, "mimic_with_baselines.csv")
    if not os.path.exists(p):
        raise SystemExit(f"missing {p}; it carries the comparator standard "
                         "errors and there is no fallback for them")
    b = pd.read_csv(p).set_index("method")
    return {m: float(b.loc[m, "se"]) for m in BASELINES}


def fmt(mean, sd):
    """Show the across-seed spread only where there is one.

    Unadjusted, the covariate baseline and the two neural comparators never see
    the pre-training arm, so they return the same number for every seed. Printing
    "(0.000)" beside them suggests a spread that was measured and found to be
    zero, when in fact there is nothing for a seed to vary.
    """
    if not np.isfinite(sd) or sd < 5e-4:
        return f"{mean:.3f}"
    return f"{mean:.3f} ({sd:.3f})"


def main():
    d = pd.read_csv(os.path.join(OUT, f"full_insample_ease_{ARM}.csv"))
    d = d[d["seed"] > 0]
    n_seed = d["seed"].nunique()

    # ---- Table A: EASE by estimand, plus the individual-effect column -------
    # The ITE column carries the same quantity Figure 4 annotates -- the mean
    # within-control standard deviation of the estimated individual effects,
    # whose correct value is zero -- so the table and the figure report the same
    # methods on the same four tasks. The unadjusted analysis has no individual
    # effects to estimate and is left blank rather than scored.
    fit_path = os.path.join(OUT, f"funnel_grid_{ARM}_fits.csv")
    if os.path.exists(fit_path):
        ite = pd.read_csv(fit_path)
        ite = ite[ite["estimand"] == "ITE"][["method", "ease_mean"]]
        ite = ite.rename(columns={"ease_mean": "sd"})
    else:
        ite = pd.read_csv(os.path.join(OUT, f"ite_grid_{ARM}.csv"))
    # Bold the best value in each column, as make_adrd_table.py does -- lower
    # EASE and lower individual-effect spread are both better, and both have a
    # known correct value of zero. Bolding a fixed row instead would assert a win
    # typographically wherever the row does not in fact win.
    def col_min(est):
        v = [d[(d["method"] == k) & (d["estimand"] == est)]["ease"].mean()
             for k, _ in ROWS]
        v = [x for x in v if np.isfinite(x)]
        return min(v) if v else np.nan

    best_ease = {e: col_min(e) for e in ("ATT", "ATE", "ATC")}
    ite_vals = [ite[ite["method"] == k]["sd"].mean() for k, _ in ROWS]
    best_ite = min([x for x in ite_vals if np.isfinite(x)], default=np.nan)

    a = ["% generated by experiments/make_mimic_tables.py -- do not hand-edit",
         r"\begin{tabular}{|l|c|c|c|c|}", r"\hline",
         r"Method & ATT & ATE & ATC & ITE spread \\", r"\hline"]
    for key, lab in ROWS:
        cells = []
        for est in ("ATT", "ATE", "ATC"):
            g = d[(d["method"] == key) & (d["estimand"] == est)]["ease"]
            s = fmt(g.mean(), g.std())
            cells.append(f"\\textbf{{{s}}}" if g.mean() == best_ease[est] else s)
        t = ite[ite["method"] == key]["sd"]
        if not len(t):
            cells.append("---")
        else:
            s = f"{t.mean():.3f}"
            cells.append(f"\\textbf{{{s}}}" if t.mean() == best_ite else s)
        a.append(f"{lab} & " + " & ".join(cells) + r" \\")
    a += [r"\hline", r"\end{tabular}"]

    # ---- Table B: risk ratios, combined population ------------------------
    # No "distance removed" column. The `closed` field in the results file is
    # 100*(1 - |logRR|/|log 1.801|), the proportion of the *crude* association
    # removed, whose denominator is this cohort's own confounded estimate rather
    # than any external quantity; it measures movement toward the null, which is
    # the shrinkage that a negative-control diagnostic cannot distinguish from
    # debiasing. Rescaling it against the published 0.80 does not repair this,
    # since that value is a hazard ratio from a different design and time origin
    # and is not a target for a risk ratio. The column is therefore omitted and
    # the debiasing claim rests on EASE and on the semi-synthetic benchmark,
    # where the truth is known by construction.
    # Nothing is bolded here. A risk ratio has no better or worse value without
    # a known truth, and this cohort has none; bolding one row would assert a
    # ranking the table cannot support.
    bse = base_se()
    b = ["% generated by experiments/make_mimic_tables.py -- do not hand-edit",
         r"\begin{tabular}{|l|c|c|c|}", r"\hline",
         r"Method & RR & 95\% CI & SE \\", r"\hline"]
    for key, lab in ROWS:
        g = d[(d["method"] == key) & (d["estimand"] == "ATE")]
        logrr = g["logrr"].mean()
        se = bse.get(key, g["se"].mean())
        rr = np.exp(logrr)
        lo, hi = np.exp(logrr - 1.96 * se), np.exp(logrr + 1.96 * se)
        b.append(f"{lab} & {rr:.3f} & {lo:.3f}--{hi:.3f} & {se:.3f} " + r"\\")
    b += [r"\hline", r"\end{tabular}"]

    for name, body in (("tab_mimic_ease", a), ("tab_mimic_rr", b)):
        p = os.path.join(OUT, name + ".tex")
        with open(p, "w", encoding="utf-8") as f:
            f.write("\n".join(body) + "\n")
        print(f"-> {p}")

    print(f"\nARM={ARM}, mean over {n_seed} seeds\n")
    print("\n".join(a[3:-2]).replace("\\\\", "").replace("\\methodName", "RWE-T"))
    print()
    print("\n".join(b[3:-2]).replace("\\\\", "").replace("\\methodName", "RWE-T"))


if __name__ == "__main__":
    main()
